title: "Grow With Boss"
description: "Insights, strategies, and stories to help you grow smarter ðŸš€"
url: "https://growwithboss.github.io/blog"
baseurl: ""

theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - .github/
  - scripts/
  - blog.csv
  - LICENSE
  - requirements.txt

markdown: kramdown
