title: "BOSS BLOG"
description: "Insights, stories, and lessons from BOSS"
theme: minima

url: "https://growwithboss.github.io"
baseurl: "/blog"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true

markdown: kramdown

# Custom styles
sass:
  style: compressed
