title: "Grow With Boss"
description: "Insights, strategies, and stories to help you grow smarter ðŸš€"
url: "https://growwithboss.github.io/blog"
baseurl: ""

theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Grow With Boss"
  email: "growwithboss@gmail.com"

markdown: kramdown
